version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    # Puxa todas as variáveis do arquivo de uma vez
    env_file: 
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: ./backend       
    restart: always
    env_file: 
      - .env
    ports:
      - "3333:3333"
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  mysql_data: